Tasks implement-queue-using-stacks and binary-tree-tilt
coding-like-a-pro/leetcode pull request #1
Opened 2020-11-27 22:57 UTC by saloev

1. https://leetcode.com/problems/implement-queue-using-stacks/ 
O(n^2) 

2. https://leetcode.com/problems/binary-tree-tilt/
O(n^2)

2020-11-27 23:29 UTC, MekhrubonT commented on saloev/implement-queue-using-stacks.ts
> +  private stack: MyStack;
Bad naming

2020-11-27 23:40 UTC, MekhrubonT requested changes

2020-11-27 23:40 UTC, MekhrubonT commented on saloev/implement-queue-using-stacks.ts
> +class MyQueue {
Плохая асимптотика, давай используем вот этот алгоритм, который работает за O(1) в среднем и достаточно просто реализуется: http://neerc.ifmo.ru/wiki/index.php?title=%D0%9E%D1%87%D0%B5%D1%80%D0%B5%D0%B4%D1%8C

2020-11-27 23:40 UTC, MekhrubonT commented on saloev/implement-queue-using-stacks.ts
> +    if (!this.needToReverse) this.reverseStack();
push и pop  оба используют какую то логику с needToReverse, но в одном случае ты вынес в функцию, а в другом нет.

2020-11-27 23:40 UTC, MekhrubonT commented on saloev/binary-tree-tilt.ts
> +    const sum = [left, right]
This is not sum.

2020-11-27 23:40 UTC, MekhrubonT commented on saloev/binary-tree-tilt.ts
> +      .map(sumTree)
Можно соптимизировать это решение, если не считать сумму поддерева каждый раз заново, а вместо этого использовать iter. 
leftSum = iter(left);
rightSum = iter(right);
sum = leftSum + rightSum + this.val
this.val = ...
return sum

2020-11-27 23:40 UTC, MekhrubonT commented on saloev/binary-tree-tilt.ts
> +
По хорошему бы новое дерево создавать конечно, а не переиспользовать старое.

2020-11-28 19:23 UTC, saloev commented on saloev/image-smoother.ts
> +function imageSmoother(M: number[][]): number[][] {
O(n*m)

2020-11-28 19:24 UTC, saloev commented on saloev/intersection-of-two-arrays-ii.ts
> +function intersect(nums1: number[], nums2: number[]): number[] {
O(n)

2020-11-28 19:26 UTC, saloev commented on saloev/binary-tree-tilt.ts
> +      .map(sumTree)
Не совсем понял, нужно еще один iter сдлать для опдсчета суммы ? или в этой же функции  ?

2020-11-29 17:55 UTC, closed without merging